function A1 = A1func(l1,l2,l3,q1,q2,q3,q5,q8,q11)
%A1func
%    A1 = A1func(L1,L2,L3,Q1,Q2,Q3,Q5,Q8,Q11)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    07-Aug-2022 23:19:37

t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = sin(q1);
t6 = sin(q2);
t7 = sin(q3);
t8 = l1+q5;
t9 = l2+q8;
t10 = l3+q11;
A1 = reshape([-t5.*t8,-t6.*t9,t7.*t10,0.0,t2,0.0,0.0,t3,0.0,0.0,-t4,0.0,t2.*t8,t3.*t9,-t4.*t10,0.0,t5,0.0,0.0,t6,0.0,0.0,-t7,0.0],[12,2]);
