function out1 = Efunc(dq1,dq2,dq3,g,l1,l2,l3,m1,m2,m3,q1,q2,q3)
%Efunc
%    OUT1 = Efunc(DQ1,DQ2,DQ3,G,L1,L2,L3,M1,M2,M3,Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    07-Aug-2022 19:45:27

t2 = sin(q1);
t3 = dq1.^2;
t4 = l1.^2;
out1 = (dq2.^2.*l2.^2.*m2)./6.0+(dq3.^2.*l3.^2.*m3)./6.0+(m1.*t3.*t4)./6.0+(m2.*t3.*t4)./2.0+(g.*l1.*m1.*t2)./2.0+g.*l1.*m2.*t2+(g.*l2.*m2.*sin(q2))./2.0+(g.*l3.*m3.*sin(q3))./2.0+(dq1.*dq2.*l1.*l2.*m2.*cos(q1-q2))./2.0;
