function H_matrix = Hfunc(dq1,dq2,g,l1,l2,l3,m1,m2,m3,q1,q2,q3)
%Hfunc
%    H_matrix = Hfunc(DQ1,DQ2,G,L1,L2,L3,M1,M2,M3,Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    07-Aug-2022 19:45:26

t2 = cos(q1);
t3 = -q2;
t4 = q1+t3;
t5 = sin(t4);
H_matrix = [(l1.*(g.*m1.*t2+g.*m2.*t2.*2.0+dq2.^2.*l2.*m2.*t5))./2.0;(l2.*m2.*(g.*cos(q2)-dq1.^2.*l1.*t5))./2.0;(g.*l3.*m3.*cos(q3))./2.0];
