function M = Mfunc(l1,l2,l3,m1,m2,m3,q1,q2)
%Mfunc
%    M = Mfunc(L1,L2,L3,M1,M2,M3,Q1,Q2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    07-Aug-2022 19:45:24

t2 = -q2;
t3 = q1+t2;
t4 = cos(t3);
t5 = (l1.*l2.*m2.*t4)./2.0;
M = reshape([(l1.^2.*(m1+m2.*3.0))./3.0,t5,0.0,t5,(l2.^2.*m2)./3.0,0.0,0.0,0.0,(l3.^2.*m3)./3.0],[3,3]);
